'use client';

import { useMemo, useState } from 'react';

export default function MockContractButton({
  contractLabel,
  details,
}: {
  contractLabel: string;
  details: Record<string, any>;
}) {
  const [open, setOpen] = useState(false);
  const pretty = useMemo(() => {
    try {
      return JSON.stringify(details, null, 2);
    } catch {
      return String(details);
    }
  }, [details]);

  const downloadMock = () => {
    const w = window.open('', '_blank', 'noopener,noreferrer,width=920,height=720');
    if (!w) return;
    w.document.write(`
      <html>
        <head>
          <title>${contractLabel}</title>
          <style>
            body{font-family:Arial,Helvetica,sans-serif;margin:32px;color:#111}
            h1{font-size:22px;margin-bottom:8px}
            .meta{color:#444;font-size:13px;margin-bottom:18px}
            pre{background:#f6f7f9;border:1px solid #e5e7eb;padding:14px;border-radius:12px;overflow:auto}
            .hint{color:#666;font-size:12px;margin-top:12px}
            @media print{ .hint{display:none} }
          </style>
        </head>
        <body>
          <h1>${contractLabel}</h1>
          <div class="meta">Mock contract generated by ODOP Connect • ${new Date().toLocaleString()}</div>
          <pre>${pretty.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
          <div class="hint">Use your browser print dialog to save as PDF.</div>
          <script>window.onload=()=>{window.focus();window.print();}</script>
        </body>
      </html>
    `);
    w.document.close();
  };

  return (
    <>
      <button type="button" onClick={() => setOpen(true)} className="btn btn-outline">
        {contractLabel}
      </button>
      {open ? (
        <div className="fixed inset-0 z-[100] bg-black/40 flex items-center justify-center p-4">
          <div className="glass-card border border-white/20 rounded-3xl w-full max-w-md p-5">
            <p className="font-display font-bold text-gray-900 dark:text-white">
              Generate mock contract
            </p>
            <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">
              This creates a printable contract page (save as PDF from print dialog).
            </p>
            <div className="mt-5 flex gap-3">
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="btn btn-outline flex-1"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => {
                  setOpen(false);
                  downloadMock();
                }}
                className="btn btn-primary flex-1"
              >
                Download
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}

